plugins:
  - serverless-plugin-typescript

service: discogs-collection
provider:
  name: aws
  runtime: nodejs6.10
  stage: dev
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - cloudwatch:PutMetricData
      Resource:
        - "*"

custom:
  fallback:
    username: sbstjn
  stage: ${opt:stage, self:provider.stage}
  username: ${env:USERNAME, self:custom.fallback.username}

functions:
  value:
    handler: functions/value.handler
    environment:
      TOKEN: ${env:TOKEN}
      USERNAME: ${self:custom.username}
    events:
      - schedule: rate(10 minutes)
  items:
    handler: functions/items.handler
    environment:
      TOKEN: ${env:TOKEN}
      USERNAME: ${self:custom.username}
    events:
      - schedule: rate(10 minutes)

  http-last:
    handler: routes/last.handler
    environment:
      TOKEN: ${env:TOKEN}
      USERNAME: ${self:custom.username}
    events:
      - http: GET last

package:
  exclude:
    - tests/**/*
    - coverage/**/*
    - node_modules/**/*
  include:
    - node_modules/encoding/**/*
    - node_modules/iconv-lite/**/*
    - node_modules/is-stream/**/*
    - node_modules/isomorphic-fetch/**/*
    - node_modules/node-fetch/**/*